import path from "node:path";
import { isDeepStrictEqual } from "node:util";

import { isSafeRepositoryPath } from "@mokly/viewer/data";
import type { Manifest } from "@mokly/viewer/data";

import { compileCatalogue } from "../build/compile.js";
import { generatedBytes, type GeneratedFile } from "../build/generated_file.js";
import { isInside, projectRealPath } from "../config/paths.js";
import { privateStaticPathReason } from "../config/public_files.js";
import type { ResolvedConfig } from "../config/types.js";
import { MoklyError } from "../errors.js";

import {
  FileSystemReviewAssetReader,
  type LocatedReviewAsset,
} from "./assets.js";

/** Generated bytes come from an accepted compilation; only public resources use disk. */
export class CompiledReviewAssetReader extends FileSystemReviewAssetReader {
  constructor(
    private readonly headConfig: ResolvedConfig,
    private readonly outputs?: ReadonlyMap<string, GeneratedFile>,
  ) {
    super(headConfig);
  }

  override async readLocated(route: string): Promise<LocatedReviewAsset> {
    const content = this.outputs?.get(route);
    if (content === undefined) return super.readLocated(route);
    const logicalPath = path.resolve(this.headConfig.mockupsDir, route);
    if (
      !isSafeRepositoryPath(route) ||
      !isInside(this.headConfig.mockupsDir, logicalPath)
    )
      throw new MoklyError(
        "review-invalid",
        `Generated comparison resource is not public: ${route} (unsafe path)`,
      );
    const denial = privateStaticPathReason(logicalPath, this.headConfig);
    if (denial)
      throw new MoklyError(
        "review-invalid",
        `Generated comparison resource is not public: ${route} (${denial})`,
      );
    return {
      content: generatedBytes(content),
      location: {
        logicalPath,
        physicalPath: path.resolve(
          projectRealPath(this.headConfig.mockupsDir),
          route,
        ),
        relativePath: route,
        physicalRelativePath: route,
      },
    };
  }
}

/** Direct non-HTTP callers may compile once; workers supply their accepted output. */
export async function derivedHeadOutputs(
  config: ResolvedConfig,
  manifest: Manifest,
  outputs?: ReadonlyMap<string, GeneratedFile>,
): Promise<ReadonlyMap<string, GeneratedFile> | undefined> {
  if (config.generatedOutput !== "derived") return;
  if (outputs) return outputs;
  const compilation = await compileCatalogue(config);
  if (!isDeepStrictEqual(compilation.manifest, manifest))
    throw new MoklyError(
      "review-invalid",
      "Catalogue changed before comparison classification",
    );
  return compilation.outputs;
}
