import path from "node:path";

import { generatedBytes, type GeneratedFile } from "../build/generated_file.js";
import { loadConsumerGraph } from "../build/load_graph.js";
import { isValidGeneratedRoute } from "../build/styles/routes.js";
import { toPosixPath } from "../config/paths.js";
import type { ResolvedConfig } from "../config/types.js";

import type { GitReviewAssetReader, ReviewAssetReader } from "./assets.js";
import { asChangeEvidence, type ChangeEvidence } from "./change_evidence.js";

const generatedRoot = "mokly-generated";

/** Merge Git changes with generated-byte evidence without over-attributing sources. */
export async function importedChangedPaths(
  config: ResolvedConfig,
  baseline: GitReviewAssetReader,
  head: ReviewAssetReader,
  authored: readonly string[],
  outputs?: ReadonlyMap<string, GeneratedFile>,
  delivered?: readonly string[],
  acceptedRoutes?: readonly string[],
): Promise<ChangeEvidence> {
  const prefix = toPosixPath(path.relative(config.repoRoot, config.mockupsDir));
  const reserved = `${prefix ? `${prefix}/` : ""}${generatedRoot}/`;
  const authoredInputs = authored.filter(
    (route) => !route.startsWith(reserved),
  );
  const graph =
    outputs === undefined && acceptedRoutes === undefined
      ? await loadConsumerGraph(config, false)
      : undefined;
  const routes = acceptedRoutes
    ? [...acceptedRoutes].filter(isValidGeneratedRoute).sort()
    : outputs
      ? [...outputs.keys()].filter(isValidGeneratedRoute).sort()
      : [...(graph?.styleOutputs.keys() ?? [])]
          .filter(isValidGeneratedRoute)
          .sort();
  const generated = await changedGeneratedStyles(
    config,
    baseline,
    head,
    routes,
    outputs,
  );
  const changedAssets = new Set(
    generated.filter((route) => route.startsWith(`${reserved}assets/`)),
  );
  if (
    delivered === undefined &&
    ((generated.some((route) => route.startsWith(`${reserved}styles/`)) &&
      authoredInputs.some((route) => /\.css$/i.test(route))) ||
      authoredInputs.some((source) =>
        changedAssets.has(`${reserved}assets/${source}`),
      ))
  )
    delivered =
      graph?.deliveredStyleSources ??
      (await loadConsumerGraph(config, false)).deliveredStyleSources;
  return asChangeEvidence(
    [
      ...new Set([
        ...withoutDeliveredSourceImpact(
          authoredInputs,
          generated,
          new Set(delivered ?? []),
          config,
        ),
        ...generated,
      ]),
    ].sort(),
  );
}

/** Compare accepted stylesheet and asset bytes to historical generated bytes. */
export async function changedGeneratedStyles(
  config: ResolvedConfig,
  baseline: GitReviewAssetReader,
  head: ReviewAssetReader,
  routes: readonly string[],
  outputs?: ReadonlyMap<string, GeneratedFile>,
): Promise<readonly string[]> {
  if (!routes.length) return [];
  const baseFiles = await baseline.readManyIfExists(routes);
  const prefix = toPosixPath(path.relative(config.repoRoot, config.mockupsDir));
  const changed: string[] = [];
  for (const route of routes) {
    const current = outputs?.get(route);
    const bytes =
      current === undefined ? await head.read(route) : generatedBytes(current);
    const before = baseFiles.get(route);
    if (before === undefined || !Buffer.from(before).equals(bytes))
      changed.push(prefix ? `${prefix}/${route}` : route);
  }
  return changed;
}

/** Preserve non-delivered CSS and sources whose public bytes did not change. */
export function withoutDeliveredSourceImpact(
  changed: readonly string[],
  generated: readonly string[],
  delivered: ReadonlySet<string>,
  config: ResolvedConfig,
): readonly string[] {
  const prefix = toPosixPath(path.relative(config.repoRoot, config.mockupsDir));
  const base = `${prefix ? `${prefix}/` : ""}${generatedRoot}/`;
  const styleChanged = generated.some((route) =>
    route.startsWith(`${base}styles/`),
  );
  const changedAssets = new Set(
    generated.filter((route) => route.startsWith(`${base}assets/`)),
  );
  return changed.filter(
    (source) =>
      !delivered.has(source) ||
      (!(/\.css$/i.test(source) && styleChanged) &&
        !changedAssets.has(`${base}assets/${source}`)),
  );
}
