/** Inputs for a comparison of one screen or one saved component variant. */
import type {
  HistoricalManifest,
  RemovedPagePreviewArtifact,
  Manifest,
  ReviewResultV3,
  ReviewArtifact,
} from "@mokly/viewer/data";

import type { CatalogueChangeSnapshot } from "../registry/changes.js";

export interface ReviewSelection {
  readonly route: string;
  readonly variantId?: string;
}

/** Explicit selection for a page proven removed by the accepted snapshot. */
export interface RemovedPageSelection {
  readonly kind: "page";
  readonly route: string;
}

/** Private evidence retained by background classification, never published as JSON. */
export interface ReviewEvidence {
  readonly baseCommit: string;
  readonly baseRef: string;
  readonly changedPaths: readonly string[];
  readonly headDigests: Readonly<Record<string, string>>;
  /** Accepted generated bytes in derived mode; pairs survive parent/child JSON IPC. */
  readonly headOutputs?: readonly (readonly [string, string])[];
}

export interface SelectedReviewSource extends ReviewEvidence {
  readonly before: Manifest;
  readonly after: Manifest;
  readonly result?: ReviewResultV3;
}

/** Pinned removal metadata and its already-validated historical manifest. */
export interface RemovedPagePreviewSource extends CatalogueChangeSnapshot {
  readonly baseline: HistoricalManifest;
}

/** Capture validated, immutable pane bytes without compiling the consumer again. */
export interface SelectedReviewProvider {
  generate(
    source: SelectedReviewSource,
    selection: ReviewSelection,
    signal: AbortSignal,
  ): Promise<ReviewArtifact>;
}

/** Capture one removed page without resolving refs or rebuilding its baseline. */
export interface RemovedPagePreviewProvider {
  generate(
    source: RemovedPagePreviewSource,
    selection: RemovedPageSelection,
    signal: AbortSignal,
  ): Promise<RemovedPagePreviewArtifact>;
}
