/** Inputs for a comparison of one screen or one saved component variant. */
import type {
  Manifest,
  ReviewResultV3,
  ReviewArtifact,
} from "@mokly/viewer/data";

export interface ReviewSelection {
  readonly route: string;
  readonly variantId?: string;
}

/** Private evidence retained by background classification, never published as JSON. */
export interface ReviewEvidence {
  readonly baseCommit: string;
  readonly baseRef: string;
  readonly changedPaths: readonly string[];
  readonly headDigests: Readonly<Record<string, string>>;
  /** Accepted generated bytes in derived mode; pairs survive parent/child JSON IPC. */
  readonly headOutputs?: readonly (readonly [string, string])[];
}

export interface SelectedReviewSource extends ReviewEvidence {
  readonly before: Manifest;
  readonly after: Manifest;
  readonly result?: ReviewResultV3;
}

/** Capture validated, immutable pane bytes without compiling the consumer again. */
export interface SelectedReviewProvider {
  generate(
    source: SelectedReviewSource,
    selection: ReviewSelection,
    signal: AbortSignal,
  ): Promise<ReviewArtifact>;
}
