import type { ComponentDesignDestination } from "../components/parts/destinations.js";

/** Stable catalogue destinations, independent of the depicted product ids. */
export const DESTINATIONS = {
  home: "design-browse-home",
  page: "design-page-view",
  pageDetails: "design-page-details",
  pageNavigation: "design-page-navigation",
  pageRemoved: "design-page-removed",
  publication: "design-publication-catalogue",
  publicationChanges: "design-publication-changes",
  welcome: "design-browse-screen",
  details: "design-browse-details-screen",
  tour: "design-browse-use-case",
  inspector: "design-browse-details",
  missing: "design-browse-missing-route",
  navigation: "design-browse-navigation",
  tagPicker: "design-browse-tag-picker",
  formsPicker: "design-browse-tag-filter",
  forms: "design-browse-tag-forms",
  onboarding: "design-browse-tag-onboarding",
  onboardingPicker: "design-browse-tag-onboarding-picker",
  darkWelcome: "design-browse-dark-scheme",
  darkDetails: "design-browse-light-only",
  appearance: "design-appearance-overview",
  appearanceLightOnly: "design-appearance-light-only",
  appearanceAuto: "design-appearance-auto",
  appearanceProps: "design-appearance-props",
  appearanceInstance: "design-appearance-instance",
  appearanceDrawer: "design-appearance-drawer",
  appearanceSideBySide: "design-appearance-side-by-side",
  appearanceDifference: "design-appearance-difference",
  appearanceHome: "design-appearance-home",
  appearanceLoading: "design-appearance-loading",
  appearanceError: "design-appearance-error",
  appearanceUnavailable: "design-appearance-unavailable",
  appearanceFlow: "design-appearance-flow",
  current: "design-changes-current",
  overlay: "design-changes-overlay",
  changed: "design-review-changed",
  added: "design-review-added",
  removed: "design-review-removed",
  difference: "design-review-difference",
  darkChanged: "design-review-dark-scheme",
  shared: "design-review-shared-impact",
  ignored: "design-review-ignored-only",
  empty: "design-review-empty",
  styleMatched: "design-review-style-matched",
  styleUnresolved: "design-review-style-unresolved",
  styleUnnamed: "design-review-style-unnamed",
  styleExcluded: "design-review-style-excluded",
  preparing: "design-review-preparing",
  unavailable: "design-review-unavailable",
} as const;

export type DesignDestination =
  (typeof DESTINATIONS)[keyof typeof DESTINATIONS] | ComponentDesignDestination;
export type ComparisonMode =
  "current" | "side-by-side" | "overlay" | "difference";
export type DepictedScheme = "light" | "dark";
