import type { ComponentDesignDestination } from "../components/parts/destinations.js";

/** Stable catalogue destinations, independent of the depicted product ids. */
export const DESTINATIONS = {
  home: "design/browse/views/home",
  exampleOverview: "design/browse/views/folder-overview",
  document: "design/browse/pages/document",
  page: "design/browse/pages/view",
  pageDetails: "design/browse/pages/details",
  pageNavigation: "design/browse/pages/navigation",
  pageRemoved: "design/browse/pages/removed",
  pageRemovedLong: "design/browse/pages/previous-version/long",
  pageRemovedLoading: "design/browse/pages/previous-version/loading",
  pageRemovedUnavailable: "design/browse/pages/previous-version/unavailable",
  publication: "design/browse/publication/catalogue",
  publicationChanges: "design/browse/publication/changes",
  welcome: "design/browse/views/screen",
  welcomeAppearanceVariant: "design/browse/views/screen/dark-scheme",
  detailsAppearanceVariant: "design/browse/views/screen/light-only",
  details: "design/browse/views/details-screen",
  tour: "design/browse/views/use-case",
  inspector: "design/browse/states/details",
  missing: "design/browse/states/missing-route",
  navigation: "design/browse/states/navigation",
  variantSelected: "design/browse/variants/variant-selected",
  variantChanges: "design/browse/variants/variant-changes",
  variantRemoved: "design/browse/variants/variant-removed",
  variantReparented: "design/browse/variants/variant-reparented",
  changedViews: "design/browse/variants/changed-views",
  indexEntry: "design/browse/index-entries/screen",
  indexMember: "design/browse/index-entries/member",
  indexEntryChanges: "design/browse/index-entries/screen-changes",
  indexMemberChanges: "design/browse/index-entries/member-changes",
  tagPicker: "design/browse/views/screen/tag-picker",
  formsPicker: "design/browse/states/tag-filter",
  forms: "design/browse/views/screen/tag-forms",
  onboarding: "design/browse/views/screen/tag-onboarding",
  onboardingPicker: "design/browse/views/screen/tag-onboarding-picker",
  appearance: "design/browse/appearance/overview",
  appearanceLightOnly: "design/browse/appearance/states/light-only",
  appearanceAuto: "design/browse/appearance/states/auto",
  appearanceLightOnlyDocument:
    "design/browse/appearance/states/light-only-document",
  appearanceProps: "design/browse/appearance/workspaces/props",
  appearanceInstance: "design/browse/appearance/workspaces/instance",
  appearanceDrawer: "design/browse/appearance/workspaces/drawer",
  appearanceSideBySide: "design/browse/appearance/workspaces/side-by-side",
  appearanceDifference: "design/browse/appearance/workspaces/difference",
  appearanceHome: "design/browse/appearance/status/home",
  appearanceLoading: "design/browse/appearance/status/loading",
  appearanceError: "design/browse/appearance/status/error",
  appearanceUnavailable: "design/browse/appearance/status/unavailable",
  appearanceFlow: "design/browse/appearance/status/flow",
  current: "design/changes/diff-controls/current",
  overlay: "design/changes/diff-controls/overlay",
  overlayLong: "design/changes/diff-controls/overlay-long",
  overlayPanel: "design/changes/diff-controls/overlay-panel",
  sideBySideApart: "design/changes/diff-controls/side-by-side-apart",
  changed: "design/changes/outcomes/changed",
  moved: "design/changes/outcomes/moved",
  added: "design/changes/outcomes/added",
  removed: "design/changes/outcomes/removed",
  removedLong: "design/changes/outcomes/previous-version/long",
  removedLoading: "design/changes/outcomes/previous-version/loading",
  removedUnavailable: "design/changes/outcomes/previous-version/unavailable",
  removedNoView: "design/changes/outcomes/previous-version/no-view",
  difference: "design/changes/outcomes/difference",
  shared: "design/changes/impact/shared-impact",
  ignored: "design/changes/impact/ignored-only",
  empty: "design/changes/impact/empty",
  styleMatched: "design/changes/impact/styles/matched",
  styleUnresolved: "design/changes/impact/styles/unresolved",
  styleUnnamed: "design/changes/impact/styles/unnamed",
  styleExcluded: "design/changes/impact/styles/excluded",
  preparing: "design/changes/availability/preparing",
  unavailable: "design/changes/availability/unavailable",
} as const;

export type DesignDestination =
  (typeof DESTINATIONS)[keyof typeof DESTINATIONS] | ComponentDesignDestination;
export type ComparisonMode =
  "current" | "side-by-side" | "overlay" | "difference";
