import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import { generatedHeader, generatedSource } from "../dist/build/ownership.js";
import { loadConfig } from "../dist/config/load.js";

import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

test("ownership headers encode every comment-unsafe source path", () => {
  for (const source of [
    "entries/a-->b.mockup.tsx",
    "entries/a--b.mockup.tsx",
    "entries/a<b.mockup.tsx",
    "entries/a>b.mockup.tsx",
  ]) {
    const header = generatedHeader(source);
    const body = header.slice("<!--".length, header.indexOf("-->"));

    assert.equal(generatedSource(header), source);
    assert.doesNotMatch(body, /--|<|>/);
    assert.equal(generatedSource(header.replace("\n", "\r\n")), source);
  }
});

test("ownership parsing migrates only comment-safe legacy headers", () => {
  const safe =
    "<!-- Generated by mokly from entries/fixture.mockup.tsx. Do not edit. -->\r\n";
  assert.equal(generatedSource(safe), "entries/fixture.mockup.tsx");

  for (const source of [
    "entries/a-->b.mockup.tsx",
    "entries/a--b.mockup.tsx",
    "entries/a<b.mockup.tsx",
    "entries/a>b.mockup.tsx",
  ]) {
    assert.equal(
      generatedSource(
        `<!-- Generated by mokly from ${source}. Do not edit. -->\n`,
      ),
      undefined,
    );
  }
});

test("ownership parsing recognizes former Mokabook generated headers", () => {
  const source = "entries/fixture.mockup.tsx";
  const encoded = Buffer.from(source, "utf8").toString("base64");
  assert.equal(
    generatedSource(
      `<!-- Generated by mokabook; ownership=v1; source-base64=${encoded}. Do not edit. -->\n`,
    ),
    source,
  );
  assert.equal(
    generatedSource(
      `<!-- Generated by mokabook from ${source}. Do not edit. -->\n`,
    ),
    source,
  );
});

test("catalogue output safely owns a comment-unsafe entry filename", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const unsafePath = path.join(fixture.entriesDir, "a-->b.mockup.tsx");
  await fs.promises.rename(fixture.entryPath, unsafePath);
  await fs.promises.writeFile(unsafePath, validEntrySource());

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const output =
    textOutput(compilation.outputs, "screens/home.mobile.html") ?? "";
  const header = output.slice(0, output.indexOf("\n") + 1);

  assert.equal(generatedSource(header), "entries/a-->b.mockup.tsx");
  assert.equal(header.match(/-->/g)?.length, 1);
  assert.doesNotMatch(header.slice(4, header.indexOf("-->")), /--|<|>/);
});
