import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { checkCompilation } from "../dist/build/check.js";
import { compileCatalogue } from "../dist/build/compile.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";
import {
  parseManifest,
  parseHistoricalManifest,
} from "../dist/registry/manifest.js";

import {
  createFixture,
  removeFixture,
  repositoryRoot,
  validEntrySource,
} from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

test("build renders deterministic fragments, resolves id links, and checks committed bytes", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const first = await compileCatalogue(config);
  await writeCompilation(first, config);
  checkCompilation(await compileCatalogue(config), config);
  const home = await fs.promises.readFile(
    path.join(fixture.mockupsDir, "screens/home.mobile.html"),
    "utf8",
  );
  assert.match(home, /href="\.\/details\.mobile\.html"/);
  assert.equal(home.includes(fixture.root), false);
  const second = await compileCatalogue(config);
  assert.deepEqual([...second.outputs], [...first.outputs]);
});

test("custom renderer shares consumer React context and injects collected styles", async () => {
  const config = await loadConfig(
    repositoryRoot,
    "examples/basic/mokly.config.ts",
  );
  const compilation = await compileCatalogue(config);
  const mobile =
    textOutput(compilation.outputs, "screens/welcome.mobile.html") ?? "";
  assert.match(mobile, /data-example-renderer="mobile"/);
  assert.match(mobile, /data-color-scheme="light"/);
  assert.match(
    mobile,
    /<style>html\{color-scheme:light\}body\{margin:0;background:#f7f7f3\}<\/style>/,
  );
  assert.equal(mobile.includes(repositoryRoot), false);
});

test("dark schemes render dark fragments per view", async (context) => {
  const fixture = await createFixture(
    validEntrySource().replace(
      'defineScreen({ ...metadata, description: "Detail screen"',
      'defineScreen({ ...metadata, colorSchemes: ["light"], description: "Detail screen"',
    ),
    { extraConfig: 'colorSchemes: ["light", "dark"],' },
  );
  context.after(() => removeFixture(fixture));

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  for (const route of [
    "screens/home.mobile.html",
    "screens/home.desktop.html",
    "screens/home.mobile.dark.html",
    "screens/home.desktop.dark.html",
  ]) {
    assert.ok(compilation.outputs.has(route), `missing ${route}`);
  }
  assert.equal(
    textOutput(compilation.outputs, "screens/home.mobile.dark.html"),
    textOutput(compilation.outputs, "screens/home.mobile.html"),
  );
  const home = compilation.manifest.entries.find(
    (entry) => entry.id === "home",
  );
  const details = compilation.manifest.entries.find(
    (entry) => entry.id === "details",
  );
  assert.equal(home?.kind, "screen");
  assert.deepEqual(home?.kind === "screen" ? home.darkFragments : undefined, {
    desktop: "screens/home.desktop.dark.html",
    mobile: "screens/home.mobile.dark.html",
  });
  assert.equal(
    details?.kind === "screen" ? details.darkFragments : undefined,
    undefined,
  );
  assert.deepEqual(
    [...compilation.outputs.keys()].filter((route) =>
      route.startsWith("screens/details."),
    ),
    ["screens/details.mobile.html", "screens/details.desktop.html"],
  );
});

test("manifest readers accept version 2 only through explicit compatibility", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const legacy = {
    ...compilation.manifest,
    generatedBy: undefined,
    schemaVersion: 2,
    legacyPages: [],
  };
  assert.throws(() => parseManifest(legacy), /schema version 5/);
  assert.equal(parseHistoricalManifest(legacy, true).schemaVersion, 3);
});

test("check groups missing, stale, and proven orphan output", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.rm(
    path.join(fixture.mockupsDir, "screens/home.mobile.html"),
  );
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "screens/home.desktop.html"),
    "stale\n",
  );
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "orphan.html"),
    "<!-- Generated by mokly from entries/old.mockup.tsx. Do not edit. -->\n<html></html>\n",
  );
  assert.throws(
    () => checkCompilation(compilation, config),
    /missing generated files[\s\S]*stale generated files[\s\S]*orphan generated files/,
  );
});

test("invalid source leaves every last-good generated byte unchanged", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await writeCompilation(await compileCatalogue(config), config);
  const before = await treeDigest(fixture.mockupsDir);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({ body: `<a href="mock:missing-screen">Broken</a>` }),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /unknown id: missing-screen/,
  );
  assert.equal(await treeDigest(fixture.mockupsDir), before);
});

test("registry rejects duplicate ids, broken relationships, and fragment collisions", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace('id: "details"', 'id: "home"'),
  );
  const config = await loadConfig(fixture.root);
  await assert.rejects(() => compileCatalogue(config), /duplicate-id/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace("screens/details.html", "screens/home.html"),
  );
  await assert.rejects(() => compileCatalogue(config), /duplicate-route/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace(
      'useCaseIds: ["tour"]',
      'useCaseIds: ["missing"]',
    ),
  );
  await assert.rejects(() => compileCatalogue(config), /missing-use-case/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace(
      "screens/details.html",
      "screens/home.mobile.html",
    ),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /fragment route collides/,
  );

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace("screens/details.html", "../details.html"),
  );
  await assert.rejects(() => compileCatalogue(config), /invalid-route/);
});

test("registry reports malformed relationship arrays without leaking a TypeError", async (context) => {
  const fixture = await createFixture(`
import { defineCollection } from "@mokly/mokly";
export const mockups = [defineCollection({
  childIds: null as unknown as string[],
  dependencies: [],
  description: "Malformed collection",
  id: "malformed",
  relatedDocs: [],
  title: "Malformed"
})];
`);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await assert.rejects(
    () => compileCatalogue(config),
    /childIds must be an array of strings/,
  );
});

test("registry builds an empty structural collection", async (context) => {
  const fixture = await createFixture(`
import { defineCollection } from "@mokly/mokly";
export const mockups = [defineCollection({
  childIds: [],
  dependencies: [],
  description: "Retained navigation identity",
  id: "retained-empty",
  relatedDocs: [],
  title: "Retained empty"
})];
`);
  context.after(() => removeFixture(fixture));

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const collection = compilation.manifest.entries.find(
    (entry) => entry.id === "retained-empty",
  );
  assert.equal(collection?.kind, "collection");
  assert.deepEqual(
    collection?.kind === "collection" ? collection.childIds : undefined,
    [],
  );
});

async function treeDigest(root: string): Promise<string> {
  const files = await listFiles(root);
  const hash = crypto.createHash("sha256");
  for (const file of files) {
    hash.update(path.relative(root, file));
    hash.update(await fs.promises.readFile(file));
  }
  return hash.digest("hex");
}

async function listFiles(root: string): Promise<string[]> {
  const entries = await fs.promises.readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const candidate = path.join(root, entry.name);
      return entry.isDirectory() ? listFiles(candidate) : [candidate];
    }),
  );
  return files.flat().sort();
}
