import assert from "node:assert/strict";
import crypto from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { checkCompilation } from "../dist/build/check.js";
import { compileCatalogue } from "../dist/build/compile.js";
import { generatedHeader } from "../dist/build/ownership.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";

import { entryAt } from "./helpers/catalogue_selection.js";
import {
  createFixture,
  removeFixture,
  repositoryRoot,
  validEntrySource,
} from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

test("build renders deterministic fragments, resolves id links, and checks committed bytes", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const first = await compileCatalogue(config);
  assert.deepEqual(first.diagnostics, []);
  await writeCompilation(first, config);
  checkCompilation(await compileCatalogue(config), config);
  const home = await fs.promises.readFile(
    path.join(fixture.mockupsDir, "home/index.mobile.html"),
    "utf8",
  );
  assert.match(home, /href="\.\.\/details\/index\.mobile\.html"/);
  assert.equal(home.includes(fixture.root), false);
  const second = await compileCatalogue(config);
  assert.deepEqual(second.diagnostics, []);
  assert.deepEqual([...second.outputs], [...first.outputs]);
});

test("custom renderer shares consumer React context and injects collected styles", async () => {
  const config = await loadConfig(
    repositoryRoot,
    "examples/basic/mokly.config.ts",
  );
  const compilation = await compileCatalogue(config);
  const mobile =
    textOutput(
      compilation.outputs,
      "example/screens/welcome/index.mobile.html",
    ) ?? "";
  assert.match(mobile, /data-example-renderer="mobile"/);
  assert.match(mobile, /data-color-scheme="light"/);
  assert.match(
    mobile,
    /<style>html\{color-scheme:light\}body\{margin:0;background:#f7f7f3\}<\/style>/,
  );
  assert.equal(mobile.includes(repositoryRoot), false);
});

test("dark schemes render dark fragments per view", async (context) => {
  const fixture = await createFixture(
    validEntrySource().replace(
      'description: "Detail screen"',
      'colorSchemes: ["light"], description: "Detail screen"',
    ),
    { extraConfig: 'colorSchemes: ["light", "dark"],' },
  );
  context.after(() => removeFixture(fixture));

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  for (const route of [
    "home/index.mobile.html",
    "home/index.desktop.html",
    "home/index.mobile.dark.html",
    "home/index.desktop.dark.html",
  ]) {
    assert.ok(compilation.outputs.has(route), `missing ${route}`);
  }
  assert.match(
    textOutput(compilation.outputs, "home/index.mobile.dark.html") ?? "",
    /details\/index\.mobile\.html/,
  );
  const home = entryAt(compilation.manifest, "home", "screen");
  const details = entryAt(compilation.manifest, "details", "screen");
  assert.equal(home?.kind, "screen");
  assert.deepEqual(home?.kind === "screen" ? home.colorSchemes : undefined, [
    "light",
    "dark",
  ]);
  assert.deepEqual(
    details?.kind === "screen" ? details.colorSchemes : undefined,
    ["light"],
  );
  assert.deepEqual(
    [...compilation.outputs.keys()].filter((route) =>
      route.startsWith("details/index."),
    ),
    ["details/index.mobile.html", "details/index.desktop.html"],
  );
});

test("check groups missing, stale, and proven orphan output", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.rm(path.join(fixture.mockupsDir, "home/index.mobile.html"));
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "home/index.desktop.html"),
    "stale\n",
  );
  await fs.promises.writeFile(
    path.join(fixture.mockupsDir, "orphan.html"),
    generatedHeader("entries/old.mockup.tsx") + "<html></html>\n",
  );
  assert.throws(
    () => checkCompilation(compilation, config),
    /missing generated files[\s\S]*stale generated files[\s\S]*orphan generated files/,
  );
});

test("invalid source leaves every last-good generated byte unchanged", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  await writeCompilation(await compileCatalogue(config), config);
  const before = await treeDigest(fixture.mockupsDir);
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource({ body: `<a href="mock:missing-screen">Broken</a>` }),
  );
  await assert.rejects(
    () => compileCatalogue(config),
    /link target missing-screen does not exist/,
  );
  assert.equal(await treeDigest(fixture.mockupsDir), before);
});

test("registry rejects duplicate ids and broken relationships", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace('path: "details"', 'path: "home"'),
  );
  const config = await loadConfig(fixture.root);
  await assert.rejects(() => compileCatalogue(config), /duplicate-path/);

  await fs.promises.writeFile(
    fixture.entryPath,
    validEntrySource().replace(
      'useCasePaths: ["tour"]',
      'useCasePaths: ["missing"]',
    ),
  );
  await assert.rejects(() => compileCatalogue(config), /missing-use-case/);
});

async function treeDigest(root: string): Promise<string> {
  const files = await listFiles(root);
  const hash = crypto.createHash("sha256");
  for (const file of files) {
    hash.update(path.relative(root, file));
    hash.update(await fs.promises.readFile(file));
  }
  return hash.digest("hex");
}

async function listFiles(root: string): Promise<string[]> {
  const entries = await fs.promises.readdir(root, { withFileTypes: true });
  const files = await Promise.all(
    entries.map(async (entry) => {
      const candidate = path.join(root, entry.name);
      return entry.isDirectory() ? listFiles(candidate) : [candidate];
    }),
  );
  return files.flat().sort();
}
