import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import {
  GENERATED_MARKER,
  stripGeneratedFirstLine,
} from "../dist/build/generated_marker.js";
import { loadConfig } from "../dist/config/load.js";

import { createFixture, removeFixture } from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

for (const basename of ["a-->b", "a--b", "a<b", "a>b"])
  test(`plain generated marker does not expose comment-unsafe source ${basename}`, async (context) => {
    const fixture = await createFixture();
    context.after(() => removeFixture(fixture));
    await fs.rename(
      fixture.entryPath,
      path.join(fixture.entriesDir, `${basename}.mockup.tsx`),
    );
    const compilation = await compileCatalogue(await loadConfig(fixture.root));
    const output = textOutput(compilation.outputs, "screens/home.mobile.html")!;
    assert.ok(output.startsWith(GENERATED_MARKER));
    assert.equal(output.slice(0, output.indexOf("\n") + 1), GENERATED_MARKER);
    assert.doesNotMatch(output, /source-base64=/);
  });

for (const product of ["mokly", "mokabook"])
  test(`historical ${product} notices remain nonmaterial data`, () => {
    for (const ending of ["\n", "\r\n"]) {
      const source = "entries/fixture.mockup.tsx";
      const encoded = Buffer.from(source).toString("base64");
      for (const header of [
        `<!-- Generated by ${product} from ${source}. Do not edit. -->`,
        `<!-- Generated by ${product}; ownership=v1; source-base64=${encoded}. Do not edit. -->`,
      ])
        assert.equal(
          stripGeneratedFirstLine(`${header}${ending}<main>Content</main>`),
          "<main>Content</main>",
        );
    }
  });
