import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import { generatedBytes } from "../dist/build/generated_file.js";
import { PlainReporter } from "../dist/cli/reporter/plain.js";
import { run } from "../dist/cli/run.js";
import { loadConfig } from "../dist/config/load.js";

import { createFixture, removeFixture } from "./helpers/fixture.js";
import { memoryTerminal } from "./helpers/terminal.js";

test("a catalogue without diagnostics keeps generated bytes and plain output unchanged", async (t) => {
  const fixture = await createFixture();
  t.after(() => removeFixture(fixture));
  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const terminal = memoryTerminal({ isTTY: false });
  const exitCode = await run(
    ["build", "--config", fixture.configPath],
    fixture.root,
    terminal.environment,
    new PlainReporter(terminal.environment),
  );

  assert.equal(exitCode, 0);
  assert.equal(
    terminal.stdout(),
    `Generated ${compilation.outputs.size} Mokly files.\n`,
  );
  assert.equal(terminal.stderr(), "");
  for (const [route, expected] of compilation.outputs)
    assert.deepEqual(
      await fs.readFile(path.join(fixture.mockupsDir, route)),
      generatedBytes(expected),
      route,
    );
});
