import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import {
  GENERATED_MARKER,
  stripGeneratedFirstLine,
} from "../dist/build/generated_marker.js";
import { loadConfig } from "../dist/config/load.js";

import { createFixture, removeFixture } from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

for (const basename of ["a-->b", "a--b", "a<b", "a>b"])
  test(`plain generated marker does not expose comment-unsafe source ${basename}`, async (context) => {
    const fixture = await createFixture();
    context.after(() => removeFixture(fixture));
    await fs.rename(
      fixture.entryPath,
      path.join(fixture.entriesDir, `${basename}.mockup.tsx`),
    );
    const compilation = await compileCatalogue(await loadConfig(fixture.root));
    const output = textOutput(compilation.outputs, "home/index.mobile.html")!;
    assert.ok(output.startsWith(GENERATED_MARKER));
    assert.equal(output.slice(0, output.indexOf("\n") + 1), GENERATED_MARKER);
    assert.doesNotMatch(output, /source-base64=/);
  });

test("only the current generated notice is stripped with LF or CRLF", () => {
  for (const ending of ["\n", "\r\n"]) {
    const current = "<!-- Generated by Mokly. Do not edit. -->" + ending;
    assert.equal(
      stripGeneratedFirstLine(current + "<main>Content</main>"),
      "<main>Content</main>",
    );
    const authored =
      "<!-- Generated by mokly from author.ts. Do not edit. -->" +
      ending +
      "<main>Content</main>";
    assert.equal(stripGeneratedFirstLine(authored), authored);
  }
});
