import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { checkCompilation } from "../dist/build/check.js";
import { compileCatalogue } from "../dist/build/compile.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";

import { createFixture, removeFixture } from "./helpers/fixture.js";

test("check treats every unexpected path as extra, regardless of its contents", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.writeFile(
    path.join(config.generatedDir, "plain.txt"),
    "unmarked",
  );
  await fs.promises.writeFile(
    path.join(config.generatedDir, "legacy.html"),
    "<!-- Generated by mokly from old.ts. Do not edit. -->\n<html></html>\n",
  );
  await fs.promises.writeFile(
    path.join(config.mockupsDir, "authored.html"),
    "<html></html>\n",
  );

  assert.throws(
    () => checkCompilation(compilation, config),
    (error: Error) => {
      assert.match(
        error.message,
        /extra generated files:\n {2}- \.generated\/legacy\.html\n {2}- \.generated\/plain\.txt/,
      );
      assert.doesNotMatch(error.message, /authored\.html/);
      return true;
    },
  );
});

test("check never follows an unexpected symlink", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.symlink(
    config.mockupsDir,
    path.join(config.generatedDir, "external"),
    "dir",
  );
  assert.throws(
    () => checkCompilation(compilation, config),
    /extra generated files:\n {2}- \.generated\/external/,
  );
});

test("check reports unexpected empty directories in the generated tree", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  await fs.promises.mkdir(path.join(config.generatedDir, "extra", "empty"), {
    recursive: true,
  });

  assert.throws(
    () => checkCompilation(compilation, config),
    /extra generated files:\n {2}- \.generated\/extra\/empty/,
  );
});
