import assert from "node:assert/strict";
import { execFile, spawn } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";
import { promisify } from "node:util";

import type { TimingEvent } from "../dist/diagnostics/timings.js";

import { changedFixture } from "./helpers/changed_fixture.js";
import { repositoryRoot } from "./helpers/fixture.js";

const exec = promisify(execFile);
const bin = path.join(repositoryRoot, "dist/cli/bin.js");
const TIMING_PREFIX = "[mokly:timing] ";

function events(stderr: string): TimingEvent[] {
  return stderr
    .split("\n")
    .filter((line) => line.startsWith(TIMING_PREFIX))
    .map((line) => JSON.parse(line.slice(TIMING_PREFIX.length)) as TimingEvent);
}

test("timed build/check/export keep stdout and generated bytes unchanged", async (t) => {
  const fixture = await changedFixture(t);
  const args = ["--config", fixture.configPath];
  const normal = await exec(process.execPath, [bin, "build", ...args]);
  assert.equal(normal.stderr, "");
  const manifest = path.join(fixture.mockupsDir, "mokly-manifest.json");
  const before = await fs.readFile(manifest, "utf8");
  const timed = await exec(process.execPath, [
    bin,
    "build",
    ...args,
    "--debug-timings",
  ]);
  assert.equal(timed.stdout, normal.stdout);
  assert.equal(await fs.readFile(manifest, "utf8"), before);
  const spans = events(timed.stderr);
  assert.ok(!spans.some((event) => event.stage.startsWith("review.")));
  for (const stage of [
    "config.load",
    "graph.bundle",
    "render",
    "html.links-and-resources",
    "output.stage",
    "output.install",
  ])
    assert.ok(
      spans.some(
        (event) =>
          event.stage === stage &&
          event.event === "end" &&
          event.status === "ok",
      ),
      stage,
    );
  const check = await exec(process.execPath, [
    bin,
    "check",
    ...args,
    "--debug-timings",
  ]);
  assert.ok(
    events(check.stderr).some((event) => event.stage === "output.check"),
  );
  assert.ok(
    !events(check.stderr).some((event) => event.stage.startsWith("review.")),
  );
  const exported = await exec(process.execPath, [
    bin,
    "export",
    ...args,
    "--base",
    "main",
    "--out",
    "site",
    "--debug-timings",
  ]);
  assert.ok(
    events(exported.stderr).some(
      (event) => event.stage === "export" && event.event === "end",
    ),
  );
});

test(
  "watched timings reach the child and continue after a source rebuild",
  { timeout: 30000 },
  async (t) => {
    const fixture = await changedFixture(t);
    const child = spawn(
      process.execPath,
      [
        bin,
        "serve",
        "--config",
        fixture.configPath,
        "--base",
        "main",
        "--port",
        "0",
        "--debug-timings",
      ],
      { stdio: ["ignore", "pipe", "pipe"] },
    );
    let stdout = "";
    let stderr = "";
    child.stdout.on("data", (chunk: Buffer) => {
      stdout += chunk.toString();
    });
    child.stderr.on("data", (chunk: Buffer) => {
      stderr += chunk.toString();
    });
    fixture.beforeRemove(async () => {
      if (child.exitCode === null && child.signalCode === null) {
        const exited = new Promise<void>((resolve) =>
          child.once("exit", () => resolve()),
        );
        child.kill("SIGTERM");
        await exited;
      }
    });
    const wait = async (predicate: () => boolean) => {
      for (let attempt = 0; attempt < 300; attempt++) {
        if (predicate()) return;
        assert.equal(child.exitCode, null, stderr);
        await new Promise((resolve) => setTimeout(resolve, 25));
      }
      assert.fail(`Timed server did not reach expected state\n${stderr}`);
    };
    await wait(() => stdout.includes("Mokly listening at"));
    assert.ok(
      events(stderr).some(
        (event) => event.role === "child" && event.stage === "server.listen",
      ),
    );
    await wait(() =>
      events(stderr).some(
        (event) => event.stage === "changes.classify" && event.event === "end",
      ),
    );
    const source = await fs.readFile(fixture.entryPath, "utf8");
    await fs.writeFile(
      fixture.entryPath,
      source.replace("Home screen", "Updated home screen"),
    );
    await wait(
      () =>
        events(stderr).filter(
          (event) => event.stage === "compile" && event.event === "end",
        ).length === 2,
    );
    await wait(
      () =>
        events(stderr).filter(
          (event) =>
            event.stage === "changes.classify" && event.event === "end",
        ).length >= 2,
    );
    assert.ok(
      events(stderr)
        .filter((event) => event.stage === "compile")
        .every((event) => event.role === "background"),
    );
    assert.equal(
      events(stderr).filter(
        (event) =>
          event.stage === "catalogue.prepare-index" && event.event === "end",
      ).length,
      2,
    );
  },
);
