import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import { loadConfig } from "../dist/config/load.js";

import {
  registerFixturePage,
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";
import { textOutput } from "./helpers/generated_text.js";

test("compatibility transforms preserve complete logical-link records", async () => {
  const mutations = [
    ["remove marker", `.replace(/ data-mokly-link="details"/, "")`],
    [
      "change marker",
      `.replace('data-mokly-link="details"', 'data-mokly-link="home"')`,
    ],
    [
      "change portable href",
      `.replace('href="../details/index.mobile.html"', 'href="../home/index.mobile.html"')`,
    ],
    [
      "remove portable href",
      `.replace(' href="../details/index.mobile.html"', "")`,
    ],
    [
      "change portable metadata href",
      `.replace('data-nav-href="../details/index.mobile.html"', 'data-nav-href="../home/index.mobile.html"')`,
    ],
    ["remove portable metadata href", `.replace(/ data-nav-href="[^"]+"/, "")`],
    ["change native link class", `.replace("<a ", "<div ")`],
    ["change namespace", `.replace("<a ", "<svg><a ")`],
    ["add marker", `.replace("<main", '<main data-mokly-link="details"')`],
  ] as const;

  for (const [label, mutation] of mutations) {
    const fixture = await createFixture(
      validEntrySource({
        body: '<a data-nav-href="mock:details" href="mock:details">Details</a>',
      }),
    );
    try {
      await writeTransformer(fixture.root, mutation);
      await assert.rejects(
        async () => compileCatalogue(await loadConfig(fixture.root)),
        /compatibility transform.*logical-reference record/,
        label,
      );
    } finally {
      await removeFixture(fixture);
    }
  }
});

test("compatibility transforms cannot duplicate reserved Browse metadata", async () => {
  for (const mutation of [
    `.replace('data-mokly-link="details"', 'data-mokly-link="details" data-mokly-link="home"')`,
    `.replace('data-mokly-link="details"', 'data-mokly-link="details" data-mokly-target="_self" data-mokly-target="_blank"')`,
  ]) {
    const fixture = await createFixture();
    try {
      await writeTransformer(fixture.root, mutation);
      await assert.rejects(
        async () => compileCatalogue(await loadConfig(fixture.root)),
        /duplicate reserved data-mokly-(?:link|target)/,
      );
    } finally {
      await removeFixture(fixture);
    }
  }
});

test("compatibility transforms preserve every generated ownership header", async () => {
  const cases = [
    {
      label: "remove a screen header",
      legacy: false,
      route: "home/index.mobile.html",
      mutation: `.replace(/^<!-- Generated by mokly[^\\n]*\\n/, "")`,
    },
    {
      label: "change a screen owner",
      legacy: false,
      route: "home/index.mobile.html",
      mutation: `.replace(/source-base64=[^.]+/, "source-base64=${Buffer.from("entries/other.mockup.tsx").toString("base64")}")`,
    },
    {
      label: "downgrade a screen header",
      legacy: false,
      route: "home/index.mobile.html",
      mutation: `.replace(/^<!-- Generated by mokly[^\\n]*\\n/, "<!-- Generated by mokly from entries/fixture.mockup.tsx. Do not edit. -->\\n")`,
    },
    {
      label: "remove a legacy header",
      legacy: true,
      route: "notice/index.html",
      mutation: `.replace(/^<!-- Generated by mokly[^\\n]*\\n/, "")`,
    },
  ] as const;

  for (const item of cases) {
    const fixture = await createFixture();
    try {
      if (item.legacy) {
        const legacyDir = path.join(fixture.root, "legacy");
        await fs.promises.mkdir(legacyDir);
        await fs.promises.writeFile(
          path.join(legacyDir, "notice.source.ts"),
          'export const source = () => "<!doctype html><html><body>Notice</body></html>";\n',
        );
      }
      if (item.legacy)
        await registerFixturePage(
          fixture,
          "notice",
          "notice.html",
          "legacy/notice.source.ts",
        );
      await writeTransformer(fixture.root, item.mutation, {
        legacy: item.legacy,
        unchangedWhen: `input.route !== ${JSON.stringify(item.route)}`,
      });

      await assert.rejects(
        async () => compileCatalogue(await loadConfig(fixture.root)),
        /generated ownership header/,
        item.label,
      );
    } finally {
      await removeFixture(fixture);
    }
  }
});

test("compatibility transforms may retain ownership with CRLF", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await writeTransformer(fixture.root, `.replace("\\n", "\\r\\n")`, {
    unchangedWhen: 'input.route !== "home/index.mobile.html"',
  });

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const mobile =
    textOutput(compilation.outputs, "home/index.mobile.html") ?? "";

  assert.match(mobile, /^<!-- Generated by mokly[^\r\n]+-->\r\n/);
});

test("identity transforms preserve metadata-only native links", async (context) => {
  const fixture = await createFixture(
    validEntrySource({
      body: '<a data-nav-href="mock:details">Details metadata</a>',
    }),
  );
  context.after(() => removeFixture(fixture));
  await writeTransformer(fixture.root, "");

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const mobile =
    textOutput(compilation.outputs, "home/index.mobile.html") ?? "";

  assert.match(
    mobile,
    /<a data-nav-href="\.\.\/details\/index\.mobile\.html">/,
  );
  assert.doesNotMatch(mobile, /data-mokly-link/);
});

test("compatibility transforms cannot add base URLs to activatable documents", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await writeTransformer(
    fixture.root,
    `.replace("<head>", '<head><base href="https://example.test/">')`,
  );

  await assert.rejects(
    async () => compileCatalogue(await loadConfig(fixture.root)),
    /base href.*activatable logical link/,
  );
});

test("compatibility transforms cannot remove an anchor from one target view", async (context) => {
  const fixture = await createFixture(fragmentSource(), {
    extraConfig: 'colorSchemes: ["light", "dark"],',
  });
  context.after(() => removeFixture(fixture));
  await writeTransformer(
    fixture.root,
    `.replace(input.route === "details/index.mobile.dark.html" ? ' id="section"' : "never", "")`,
  );

  await assert.rejects(
    async () => compileCatalogue(await loadConfig(fixture.root)),
    /logical fragment section.*missing.*mobile.*dark/,
  );
});

async function writeTransformer(
  root: string,
  mutation: string,
  options: { legacy?: boolean; unchangedWhen?: string } = {},
): Promise<void> {
  await fs.promises.writeFile(
    path.join(root, "compatibility.ts"),
    `import type { CompatibilityTransformInput } from "@mokly/mokly";
export default function transform(input: CompatibilityTransformInput): string {
  if (${options.unchangedWhen ?? 'input.route !== "home/index.mobile.html" && !input.route.includes("details")'}) return input.content;
  return input.content${mutation};
}
`,
  );
  await fs.promises.writeFile(
    path.join(root, "mokly.config.ts"),
    `export default {
  compatibility: { transformer: "compatibility.ts" },
  colorSchemes: ["light", "dark"],
  roots: [{ dir: "entries" }],
  mockupsDir: "mockups",
  repoRoot: "."
};
`,
  );
}

function fragmentSource(): string {
  return `import { defineScreen } from "@mokly/mokly";
import React from "react";
const metadata = { relatedDocs: [], useCasePaths: [] };
export const mockups = [
  defineScreen({ ...metadata, description: "Home", desktop: <main><a href="mock:details#section">Details</a></main>, path: "home", mobile: <main><a href="mock:details#section">Details</a></main>, title: "Home" }),
  defineScreen({ ...metadata, description: "Details", desktop: <main id="section">Details</main>, path: "details", mobile: <main id="section">Details</main>, title: "Details" })
];
`;
}
