import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { exportCatalogue } from "../dist/export/run.js";

import { derivedFixture } from "./helpers/derived_fixture.js";
import { validEntrySource } from "./helpers/fixture.js";

test("derived export rebuilds and pins a baseline, captures compiled head bytes and reuses its cache", async (t) => {
  const fixture = await derivedFixture(t);
  await fs.writeFile(
    fixture.entryPath,
    validEntrySource({ body: "Current compiled screen" }),
  );
  await fs.rm(fixture.mockupsDir, { recursive: true });
  const marker = path.join(
    fixture.root,
    ".mokly-cache/baselines",
    fixture.commit,
    "complete.json",
  );
  const exported = await exportCatalogue(fixture.config, {
    outDir: "site",
    adapter: {
      async transform() {
        await fs.mkdir(path.join(fixture.config.generatedDir, "screens"), {
          recursive: true,
        });
        await fs.writeFile(
          path.join(fixture.config.generatedDir, "screens/home.mobile.html"),
          "untrusted local generated bytes",
        );
      },
    },
  });
  assert.ok(exported.comparisonUrl);
  const reviewPath = path.join(exported.outDir, exported.comparisonUrl);
  const review = JSON.parse(await fs.readFile(reviewPath, "utf8"));
  assert.equal(review.baseCommit, fixture.commit);
  assert.equal(
    review.screens.find((screen: { id: string }) => screen.id === "home").state,
    "changed",
  );
  const before = await fs.readFile(
    path.join(
      path.dirname(reviewPath),
      "snapshots/before/screens/home.mobile.html",
    ),
    "utf8",
  );
  const after = await fs.readFile(
    path.join(
      path.dirname(reviewPath),
      "snapshots/after/screens/home.mobile.html",
    ),
    "utf8",
  );
  assert.doesNotMatch(before, /Current compiled screen/);
  assert.match(after, /Current compiled screen/);
  const home = await fs.readFile(
    path.join(exported.outDir, "static/.generated/screens/home.mobile.html"),
    "utf8",
  );
  assert.match(home, /Current compiled screen/);
  assert.doesNotMatch(home, /untrusted local/);
  assert.match(
    await fs.readFile(path.join(exported.outDir, "index.html"), "utf8"),
    /data-changed="true"[^>]*data-entry-id="home"/,
  );
  const cached = await fs.readFile(marker, "utf8");
  await fs.rm(
    path.join(fixture.config.generatedDir, "screens/home.mobile.html"),
  );
  await exportCatalogue(fixture.config, { outDir: "site" });
  assert.equal(await fs.readFile(marker, "utf8"), cached);
});

test("derived export preserves its previous artifact if the pinned marker disappears", async (t) => {
  const fixture = await derivedFixture(t);
  const first = await exportCatalogue(fixture.config, { outDir: "site" });
  const oldIndex = await fs.readFile(path.join(first.outDir, "index.html"));
  await assert.rejects(
    () =>
      exportCatalogue(fixture.config, {
        outDir: "site",
        adapter: {
          async transform() {
            await fs.rm(
              path.join(
                fixture.root,
                ".mokly-cache/baselines",
                fixture.commit,
                "complete.json",
              ),
            );
          },
        },
      }),
    { code: "baseline-output-invalid" },
  );
  assert.deepEqual(
    await fs.readFile(path.join(first.outDir, "index.html")),
    oldIndex,
  );
});

test("derived export still rejects concurrent authored public resource edits", async (t) => {
  const fixture = await derivedFixture(
    t,
    validEntrySource({
      body: '<link rel="stylesheet" href="../../theme.css" />',
    }),
    {
      "theme.css": "body {}",
    },
  );
  const first = await exportCatalogue(fixture.config, { outDir: "site" });
  await assert.rejects(
    () =>
      exportCatalogue(fixture.config, {
        outDir: "site",
        adapter: {
          async transform() {
            await fs.writeFile(
              path.join(fixture.mockupsDir, "theme.css"),
              "body { color: red; }",
            );
          },
        },
      }),
    /Export inputs changed/,
  );
  assert.equal(
    await fs.readFile(path.join(first.outDir, "static/theme.css"), "utf8"),
    "body {}",
  );
});

test("derived export exposes typed build failures without installing output", async (t) => {
  const fixture = await derivedFixture(t);
  const config = {
    ...fixture.config,
    review: {
      ...fixture.config.review,
      baselineBuild: [["node", "-e", "process.exit(7)"]],
    },
  };
  await assert.rejects(() => exportCatalogue(config, { outDir: "site" }), {
    code: "baseline-command-failed",
    commandIndex: 0,
    exitCode: 7,
  });
  assert.equal(
    await fs.stat(path.join(fixture.root, "site")).catch(() => undefined),
    undefined,
  );
});
