import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { exportCatalogue } from "../packages/mokly/dist/export/run.js";

import { derivedFixture } from "./helpers/derived_fixture.js";
import { directoryFiles } from "./helpers/export_fixture.js";
import { validEntrySource } from "./helpers/fixture.js";

test("current-only derived export skips history and captures compiled bytes", async (context) => {
  const fixture = await derivedFixture(context);
  await fs.rm(path.join(fixture.root, ".git"), { recursive: true });
  await fs.writeFile(
    fixture.entryPath,
    validEntrySource({ body: "Current-only compiled screen" }),
  );
  let captured: ReadonlyMap<string, Buffer> | undefined;
  const result = await exportCatalogue(fixture.config, {
    outDir: "site",
    noChanges: true,
    adapter: {
      async transform() {
        await fs.writeFile(
          path.join(fixture.mockupsDir, "home/index.mobile.html"),
          "untrusted local generated bytes",
        );
      },
    },
    capture: async (files) => {
      captured = new Map(
        [...files].map(([name, bytes]) => [name, Buffer.from(bytes)]),
      );
    },
  });
  assert.equal(result.comparisonUrl, null);
  const files = await directoryFiles(result.outDir);
  assert.deepEqual(captured, files);
  assert.match(
    files.get("static/home/index.mobile.html")!.toString(),
    /Current-only compiled screen/,
  );
  assert.doesNotMatch(
    files.get("static/home/index.mobile.html")!.toString(),
    /untrusted local/,
  );
  assert.equal(
    [...files.keys()].some((name) => name.includes("/diffs/")),
    false,
  );
  assert.doesNotMatch(
    files.get("index.html")!.toString(),
    /data-filter="changed"/,
  );
  assert.deepEqual(await fs.readdir(path.join(fixture.root, ".mokly-cache")), [
    "locks",
  ]);
});

test("current-only derived export still rejects authored edits before installation", async (context) => {
  const fixture = await derivedFixture(context, undefined, {
    "theme.css": "body {}",
  });
  const first = await exportCatalogue(fixture.config, {
    outDir: "site",
    noChanges: true,
  });
  const previous = await directoryFiles(first.outDir);
  await assert.rejects(
    exportCatalogue(fixture.config, {
      outDir: "site",
      noChanges: true,
      capture: async () => {
        await fs.writeFile(
          path.join(fixture.mockupsDir, "theme.css"),
          "body { color: red; }",
        );
      },
    }),
    /Export inputs changed/,
  );
  assert.deepEqual(await directoryFiles(first.outDir), previous);
});
