import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import {
  GENERATED_MARKER,
  stripGeneratedFirstLine,
} from "../dist/build/generated_marker.js";
import { loadConfig } from "../dist/config/load.js";
import {
  normalizeReviewPair,
  normalizeSingleDocument,
} from "../dist/review/ignore.js";

import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";

test("historical generated first lines normalize without authenticating their owner", () => {
  const html = "<html><body>Unchanged</body></html>\n";
  const encoded = Buffer.from("some/other/owner.ts", "utf8").toString("base64");
  const oldLines = [
    `<!-- Generated by mokly; ownership=v1; source-base64=${encoded}. Do not edit. -->\n`,
    `<!-- Generated by mokabook; ownership=v1; source-base64=${encoded}. Do not edit. -->\r\n`,
    "<!-- Generated by mokly from entries/old.ts. Do not edit. -->\n",
    "<!-- Generated by mokabook from entries/old.ts. Do not edit. -->\r\n",
  ];
  for (const oldLine of oldLines) {
    const pair = normalizeReviewPair(
      oldLine + html,
      GENERATED_MARKER + html,
      "screen.html",
    );
    assert.equal(pair.base, pair.head);
    assert.equal(normalizeSingleDocument(oldLine + html, "screen.html"), html);
    assert.equal(stripGeneratedFirstLine(oldLine + html), html);
  }
  assert.equal(
    stripGeneratedFirstLine(GENERATED_MARKER.replace("\n", "\r\n") + html),
    html,
  );
  assert.equal(stripGeneratedFirstLine(html), html);
});

test("generated marker is source-independent even for comment-unsafe source names", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const unsafePath = path.join(fixture.entriesDir, "a-->b.mockup.tsx");
  await fs.promises.rename(fixture.entryPath, unsafePath);
  await fs.promises.writeFile(unsafePath, validEntrySource());

  const compilation = await compileCatalogue(await loadConfig(fixture.root));
  const output = compilation.outputs.get("screens/home.mobile.html") ?? "";
  assert.ok(output.startsWith(GENERATED_MARKER));
  assert.doesNotMatch(output.slice(0, output.indexOf("\n")), /source|a-->b/);
});
