import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue, type Compilation } from "../dist/build/compile.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";

import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";

test("build rejects non-canonical related-document paths", async (context) => {
  const source = validEntrySource().replaceAll(
    'relatedDocs: ["notes.md"]',
    'relatedDocs: ["docs/../notes.md"]',
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /relatedDocs path must be a safe repository-relative path/,
  );
});

test("generated routes preserve imported authored documents outside their tree", async (context) => {
  const fixture = await createFixture(
    validEntrySource({ body: "{template}" }) +
      '\nimport template from "../mockups/home/index.mobile.html";',
    { extraConfig: 'moduleResolution:{loaders:{".html":"text"}},' },
  );
  context.after(() => removeFixture(fixture));
  await fs.promises.mkdir(path.join(fixture.mockupsDir, "home"));
  const authored = path.join(fixture.mockupsDir, "home/index.mobile.html");
  await fs.promises.writeFile(authored, "Authored template");
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  assert.ok(compilation.outputs.has("home/index.desktop.html"));
  assert.equal(
    await fs.promises.readFile(authored, "utf8"),
    "Authored template",
  );
});

test("writer rejects output missing from the inventory without touching authored roots", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await nestEntriesUnderMockups(fixture);
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set("src/entries/index.html", "<html></html>\n");
  const unsafe: Compilation = {
    ...compilation,
    manifest: {
      ...compilation.manifest,
      sourceFiles: [
        ...compilation.manifest.sourceFiles,
        "mockups/src/entries/index.html",
      ].sort(),
    },
    outputs,
  };

  await assert.rejects(
    () => writeCompilation(unsafe, config),
    /generated inventory/,
  );
  assert.equal(
    fs.existsSync(path.join(config.generatedDir, "src/entries/index.html")),
    false,
  );
  assert.equal(
    fs.existsSync(
      path.join(fixture.mockupsDir, "src/entries/fixture.mockup.tsx"),
    ),
    true,
  );
});

test("writer rejects a crafted URL-sensitive output route", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set('screens/injected" onclick="alert.html', "<html></html>\n");

  await assert.rejects(
    () => writeCompilation({ ...compilation, outputs }, config),
    /generated route is unsafe/,
  );
});

test("writer rejects stale generated bytes before staging", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  const route = compilation.manifest.generatedFiles[0]!.path;
  outputs.set(route, `${outputs.get(route)}\nchanged`);

  await assert.rejects(
    () => writeCompilation({ ...compilation, outputs }, config),
    /generated inventory has stale bytes/,
  );
  assert.equal(fs.existsSync(config.generatedDir), false);
});

test("generated routes do not follow authored-root symlinks", async (context) => {
  const source = validEntrySource().replace(
    "home/index.html",
    "linked-source/generated.html",
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  await fs.promises.symlink(
    "../entries",
    path.join(fixture.mockupsDir, "home"),
  );
  const config = await loadConfig(fixture.root);

  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  assert.ok(fs.statSync(path.join(config.generatedDir, "home")).isDirectory());
  assert.ok(
    fs.lstatSync(path.join(fixture.mockupsDir, "home")).isSymbolicLink(),
  );
});

async function nestEntriesUnderMockups(
  fixture: Awaited<ReturnType<typeof createFixture>>,
  directory = "src/entries",
): Promise<void> {
  const nestedEntries = path.join(fixture.mockupsDir, directory);
  await fs.promises.mkdir(nestedEntries, { recursive: true });
  await fs.promises.rename(
    fixture.entryPath,
    path.join(nestedEntries, "fixture.mockup.tsx"),
  );
  await fs.promises.writeFile(
    fixture.configPath,
    `export default { roots: [{dir: ${JSON.stringify(`mockups/${directory}`)}}], mockupsDir: "mockups", repoRoot: "." };\n`,
  );
}
