import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue, type Compilation } from "../dist/build/compile.js";
import { isOwned } from "../dist/build/ownership.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";

import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";

test("generated ownership belongs only to configured source roots", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const foreign = path.join(fixture.mockupsDir, "foreign.html");
  const deleted = path.join(fixture.mockupsDir, "deleted.html");
  await fs.promises.writeFile(
    foreign,
    "<!-- Generated by mokly from another-catalogue/page.mockup.tsx. Do not edit. -->\n<html></html>\n",
  );
  await fs.promises.writeFile(
    deleted,
    "<!-- Generated by mokly from entries/deleted.mockup.tsx. Do not edit. -->\r\n<html></html>\r\n",
  );

  assert.equal(isOwned(foreign, config), false);
  assert.equal(isOwned(deleted, config), true);
});

test("build rejects non-canonical repository dependency paths", async (context) => {
  const source = validEntrySource().replaceAll(
    'dependencies: ["notes.md"]',
    'dependencies: ["docs/../notes.md"]',
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /dependencies path must be a safe repository-relative path/,
  );
});

test("build rejects generated routes inside nested authored roots", async (context) => {
  const source = validEntrySource().replace(
    "screens/home.html",
    "src/entries/generated.html",
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  await nestEntriesUnderMockups(fixture);
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /generated route overlaps a resolved entry module/,
  );
});

test("writer rejects crafted output inside nested authored roots", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await nestEntriesUnderMockups(fixture);
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set("src/entries/injected.html", "<html></html>\n");
  const unsafe: Compilation = { manifest: compilation.manifest, outputs };

  await assert.rejects(
    () => writeCompilation(unsafe, config),
    /generated route overlaps a resolved entry module/,
  );
  assert.equal(
    fs.existsSync(path.join(fixture.mockupsDir, "src/entries/injected.html")),
    false,
  );
});

test("writer rejects a crafted URL-sensitive output route", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set('screens/injected" onclick="alert.html', "<html></html>\n");

  await assert.rejects(
    () => writeCompilation({ manifest: compilation.manifest, outputs }, config),
    /generated route is unsafe/,
  );
});

test("build rejects generated routes through authored-root symlinks", async (context) => {
  const source = validEntrySource().replace(
    "screens/home.html",
    "linked-source/generated.html",
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  await fs.promises.symlink(
    "../entries",
    path.join(fixture.mockupsDir, "linked-source"),
  );
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /generated route overlaps a resolved entry module/,
  );
});

async function nestEntriesUnderMockups(
  fixture: Awaited<ReturnType<typeof createFixture>>,
): Promise<void> {
  const nestedEntries = path.join(fixture.mockupsDir, "src", "entries");
  await fs.promises.mkdir(nestedEntries, { recursive: true });
  await fs.promises.rename(
    fixture.entryPath,
    path.join(nestedEntries, "fixture.mockup.tsx"),
  );
  await fs.promises.writeFile(
    fixture.configPath,
    'export default { entriesDir: "mockups/src/entries", mockupsDir: "mockups", repoRoot: "." };\n',
  );
}
