import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import test from "node:test";

import { compileCatalogue, type Compilation } from "../dist/build/compile.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";

import {
  createFixture,
  removeFixture,
  validEntrySource,
} from "./helpers/fixture.js";

test("build rejects non-canonical repository dependency paths", async (context) => {
  const source = validEntrySource().replaceAll(
    'dependencies: ["notes.md"]',
    'dependencies: ["docs/../notes.md"]',
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);

  await assert.rejects(
    () => compileCatalogue(config),
    /dependencies path must be a safe repository-relative path/,
  );
});

test("generated routes can share relative paths with nested authored roots", async (context) => {
  const source = validEntrySource().replace(
    "screens/home.html",
    "src/entries/generated.html",
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  await nestEntriesUnderMockups(fixture);
  const config = await loadConfig(fixture.root);

  const compilation = await compileCatalogue(config);
  assert.ok(compilation.outputs.has("src/entries/generated.desktop.html"));
});

test("writer rejects output missing from the inventory without touching authored roots", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  await nestEntriesUnderMockups(fixture);
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set("src/entries/injected.html", "<html></html>\n");
  const unsafe: Compilation = { manifest: compilation.manifest, outputs };

  await assert.rejects(
    () => writeCompilation(unsafe, config),
    /generated inventory/,
  );
  assert.equal(
    fs.existsSync(path.join(config.generatedDir, "src/entries/injected.html")),
    false,
  );
  assert.equal(
    fs.existsSync(
      path.join(fixture.mockupsDir, "src/entries/fixture.mockup.tsx"),
    ),
    true,
  );
});

test("writer rejects a crafted URL-sensitive output route", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  outputs.set('screens/injected" onclick="alert.html', "<html></html>\n");

  await assert.rejects(
    () => writeCompilation({ manifest: compilation.manifest, outputs }, config),
    /generated route is unsafe/,
  );
});

test("writer rejects stale generated bytes before staging", async (context) => {
  const fixture = await createFixture();
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compilation = await compileCatalogue(config);
  const outputs = new Map(compilation.outputs);
  const route = compilation.manifest.generatedFiles[0]!.path;
  outputs.set(route, `${outputs.get(route)}\nchanged`);

  await assert.rejects(
    () => writeCompilation({ manifest: compilation.manifest, outputs }, config),
    /generated inventory has stale bytes/,
  );
  assert.equal(fs.existsSync(config.generatedDir), false);
});

test("generated routes do not follow authored-root symlinks", async (context) => {
  const source = validEntrySource().replace(
    "screens/home.html",
    "linked-source/generated.html",
  );
  const fixture = await createFixture(source);
  context.after(() => removeFixture(fixture));
  await fs.promises.symlink(
    "../entries",
    path.join(fixture.mockupsDir, "linked-source"),
  );
  const config = await loadConfig(fixture.root);

  const compilation = await compileCatalogue(config);
  await writeCompilation(compilation, config);
  assert.ok(
    fs.statSync(path.join(config.generatedDir, "linked-source")).isDirectory(),
  );
  assert.ok(
    fs
      .lstatSync(path.join(fixture.mockupsDir, "linked-source"))
      .isSymbolicLink(),
  );
});

async function nestEntriesUnderMockups(
  fixture: Awaited<ReturnType<typeof createFixture>>,
): Promise<void> {
  const nestedEntries = path.join(fixture.mockupsDir, "src", "entries");
  await fs.promises.mkdir(nestedEntries, { recursive: true });
  await fs.promises.rename(
    fixture.entryPath,
    path.join(nestedEntries, "fixture.mockup.tsx"),
  );
  await fs.promises.writeFile(
    fixture.configPath,
    'export default { entriesDir: "mockups/src/entries", mockupsDir: "mockups", repoRoot: "." };\n',
  );
}
