import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";
import test from "node:test";

import { compileCatalogue } from "../dist/build/compile.js";
import { componentRuntime } from "../dist/build/component_runtime.js";
import { writeCompilation } from "../dist/build/transaction.js";
import { loadConfig } from "../dist/config/load.js";
import { captureRenderBundle } from "../dist/server/controls/transient_assets.js";
import { startCatalogueServer } from "../dist/server/http.js";
import { serve } from "../dist/server/serve.js";

import { removeFixture } from "./helpers/fixture.js";
import { entryStyle, styleFixture } from "./helpers/imported_styles_fixture.js";

for (const mode of ["committed", "derived"] as const) {
  test(`accepted ${mode} generated bytes are served without consulting stale disk`, async (context) => {
    const fixture = await styleFixture('.entry{background:url("./image.png")}');
    context.after(() => removeFixture(fixture));
    if (mode === "derived")
      await fs.writeFile(
        fixture.configPath,
        (await fs.readFile(fixture.configPath, "utf8")).replace(
          '"committed"',
          '"derived"',
        ),
      );
    const asset = "mokly-generated/assets/entries/image.png";
    await fs.writeFile(
      path.join(fixture.entriesDir, "image.png"),
      Buffer.from([0, 255]),
    );
    const scoped =
      "mokly-generated/assets/entries/node_modules/@fontsource/demo/files/font.woff2";
    const scopedFile = path.join(
      fixture.entriesDir,
      "node_modules/@fontsource/demo/files/font.woff2",
    );
    await fs.mkdir(path.dirname(scopedFile), { recursive: true });
    await fs.writeFile(scopedFile, Buffer.from([255, 0, 1]));
    await fs.appendFile(
      path.join(fixture.entriesDir, "fixture.css"),
      '.entry{src:url("./node_modules/@fontsource/demo/files/font.woff2")}',
    );
    const config = await loadConfig(fixture.root);
    const compiled = await compileCatalogue(config);
    if (mode === "committed") await writeCompilation(compiled, config);
    const stray = "mokly-generated/styles/stale.css";
    await fs.mkdir(path.join(fixture.mockupsDir, "mokly-generated/styles"), {
      recursive: true,
    });
    await fs.writeFile(path.join(fixture.mockupsDir, stray), ".stale{}");
    const server = await startCatalogueServer(config, {
      base: "main",
      port: 0,
      ...(mode === "derived"
        ? {
            manifest: compiled.manifest,
            componentRuntime: componentRuntime(compiled),
          }
        : {}),
    });
    context.after(() => server.close());
    const original = compiled.outputs.get(entryStyle) as string;
    const originalAsset = Buffer.from([0, 255]);
    for (const route of [entryStyle, asset]) {
      const file = path.join(fixture.mockupsDir, route);
      await fs.mkdir(path.dirname(file), { recursive: true });
      await fs.writeFile(file, "stale on disk");
    }
    for (const [route, expected, type] of [
      [entryStyle, Buffer.from(original), "text/css"],
      [asset, originalAsset, "image/png"],
      [scoped, Buffer.from([255, 0, 1]), "font/woff2"],
    ] as const) {
      const encoded = route.replace("@fontsource", "%40fontsource");
      const get = await fetch(`${server.url}/static/${encoded}`);
      assert.equal(get.status, 200);
      assert.match(get.headers.get("content-type") ?? "", new RegExp(type));
      assert.deepEqual(Buffer.from(await get.arrayBuffer()), expected);
      const head = await fetch(`${server.url}/static/${encoded}`, {
        method: "HEAD",
      });
      assert.equal(head.status, 200);
      assert.equal((await head.arrayBuffer()).byteLength, 0);
    }
    for (const method of ["GET", "HEAD"])
      assert.equal(
        (await fetch(`${server.url}/static/${stray}`, { method })).status,
        404,
      );
  });
}

for (const mode of ["committed", "derived"] as const)
  for (const watch of [false, true])
    test(
      `${mode} ${watch ? "watched" : "no-watch"} Serve returns accepted scoped bytes`,
      { timeout: 45_000 },
      async (context) => {
        const fixture = await styleFixture(
          '.entry{src:url("./node_modules/@fontsource/demo/files/font.woff2")}',
        );
        context.after(() => removeFixture(fixture));
        if (mode === "derived")
          await fs.writeFile(
            fixture.configPath,
            (await fs.readFile(fixture.configPath, "utf8")).replace(
              '"committed"',
              '"derived"',
            ),
          );
        const source = path.join(
          fixture.entriesDir,
          "node_modules/@fontsource/demo/files/font.woff2",
        );
        await fs.mkdir(path.dirname(source), { recursive: true });
        await fs.writeFile(source, Buffer.from([3, 0, 255]));
        const config = await loadConfig(fixture.root);
        const compiled = await compileCatalogue(config);
        if (mode === "committed") await writeCompilation(compiled, config);
        const running = await serve(config, { port: 0, watch });
        fixture.beforeRemove(() => running.close());
        const url = `${running.url}/static/mokly-generated/assets/entries/node_modules/%40fontsource/demo/files/font.woff2`;
        const get = await fetch(url);
        assert.equal(get.status, 200);
        assert.match(get.headers.get("content-type") ?? "", /font\/woff2/);
        assert.deepEqual(
          Buffer.from(await get.arrayBuffer()),
          Buffer.from([3, 0, 255]),
        );
        const head = await fetch(url, { method: "HEAD" });
        assert.equal(head.status, 200);
        assert.equal((await head.arrayBuffer()).byteLength, 0);
        const stale = path.join(
          fixture.mockupsDir,
          "mokly-generated/assets/entries/node_modules/@fontsource/demo/files/stale.woff2",
        );
        await fs.mkdir(path.dirname(stale), { recursive: true });
        await fs.writeFile(stale, "stale");
        assert.equal(
          (await fetch(url.replace("font.woff2", "stale.woff2"))).status,
          404,
        );
      },
    );

test("transient previews never read an absent generated asset from disk", async (context) => {
  const fixture = await styleFixture(".entry{color:red}");
  context.after(() => removeFixture(fixture));
  const config = await loadConfig(fixture.root);
  const compiled = await compileCatalogue(config);
  const route = [...compiled.outputs.keys()].find((candidate) =>
    candidate.endsWith(".html"),
  )!;
  const missing = "mokly-generated/assets/entries/missing.png";
  const file = path.join(fixture.mockupsDir, missing);
  await fs.mkdir(path.dirname(file), { recursive: true });
  await fs.writeFile(file, Buffer.from([3, 4]));
  const reference = path.posix.relative(path.posix.dirname(route), missing);
  const outputs = new Map(compiled.outputs);
  outputs.set(
    route,
    (compiled.outputs.get(route) as string).replace(
      "</body>",
      `<img src="${reference}" alt="preview"></body>`,
    ),
  );
  assert.throws(
    () => captureRenderBundle(route, outputs, compiled.manifest, config),
    /Preview resource|generated/,
  );
});

test("transient preview captures generated CSS and opaque bytes instead of stale disk", async (context) => {
  const fixture = await styleFixture('.entry{background:url("./image.png")}');
  context.after(() => removeFixture(fixture));
  await fs.writeFile(
    path.join(fixture.entriesDir, "image.png"),
    Buffer.from([0, 255, 3]),
  );
  const config = await loadConfig(fixture.root);
  const compiled = await compileCatalogue(config);
  const route = [...compiled.outputs.keys()].find((candidate) =>
    candidate.endsWith(".html"),
  )!;
  const asset = "mokly-generated/assets/entries/image.png";
  for (const candidate of [entryStyle, asset]) {
    const file = path.join(fixture.mockupsDir, candidate);
    await fs.mkdir(path.dirname(file), { recursive: true });
    await fs.writeFile(file, "stale disk");
  }
  const files = captureRenderBundle(
    route,
    compiled.outputs,
    compiled.manifest,
    config,
  );
  assert.deepEqual(files.get(asset)?.bytes, Buffer.from([0, 255, 3]));
  assert.equal(
    Buffer.from(files.get(entryStyle)!.bytes).toString(),
    compiled.outputs.get(entryStyle),
  );
});
