/** Browser modules that remain transport, geometry, or protocol boundaries. */
export const keep = Object.freeze([
  "catalogue_updates",
  "component_geometry",
  "component_occlusion",
  "component_overlay",
  "component_range_nodes",
  "document_ranges",
  "frame_adapter",
  "frame_error",
  "frame_mount",
  "frame_usage",
  "message_transport",
  "post_message_adapter",
  "same_origin_access",
  "same_origin_adapter",
  "same_origin_highlight",
  "same_origin_mount",
  "same_origin_pointer",
]);

/** Browser modules retired when the hydrated shell becomes the default. */
export const retire = Object.freeze([
  "browse",
  "browse_controls",
  "browse_details",
  "browse_evidence",
  "browse_fetch",
  "browse_frames",
  "browse_links",
  "browse_navigation",
  "browse_navigation_state",
  "browse_recovery",
  "browse_state",
  "browse_update_state",
  "clipboard",
  "component_controls",
  "component_highlight",
  "control_fields",
  "control_surface",
  "control_view_key",
  "diff_views",
  "diffs",
  "frame_navigation",
  "inspector_panels",
  "inspector_resize",
  "inspector_tabs",
  "navigation",
  "preview_fragment",
  "prop_display",
  "same_origin_navigation",
  "services",
  "static_delivery",
  "style_evidence",
  "tag_filter",
  "workspace",
  "workspace_events",
  "workspace_evidence",
  "workspace_evidence_data",
  "workspace_inspection",
  "workspace_preview",
  "workspace_props",
  "workspace_updates",
  "workspace_variants",
]);

/** Pure helpers that move beside the hydrated shell before retirement. */
export const move = Object.freeze(["entry_wording", "search_query"]);

/** Standalone pre-hydration modules that survive the vanilla shell deletion. */
export const retainedStandalone = Object.freeze([
  "standalone/early_disclosures",
  "standalone/nav_resize",
  "standalone/navigation_resize",
]);
