import { isSafeCatalogueRoute } from "../data/paths.js";

/** Public output directory shared by the viewer and CLI. */
export const GENERATED_DIRECTORY = "mokly-generated" as const;

/** Public resource directory shared by the viewer and CLI. */
export const VIEWER_DIRECTORY = "mokly-viewer" as const;

export type GeneratedPathPrefix = typeof GENERATED_DIRECTORY;

/** Map a logical document route to the selected publication's static path. */
export function currentDocumentPath(
  route: string,
  prefix: GeneratedPathPrefix = GENERATED_DIRECTORY,
): string {
  return `static/${prefix}/${route}`;
}

/** Reject cross-layout frame navigation before handing a route to the shell. */
export function currentDocumentRoute(
  pathname: string,
  prefix: GeneratedPathPrefix = GENERATED_DIRECTORY,
): string | undefined {
  if (/%2f|%5c/i.test(pathname)) return;
  let decoded: string;
  try {
    decoded = decodeURIComponent(pathname);
  } catch {
    return;
  }
  const root = `/${currentDocumentPath("", prefix)}`;
  if (!decoded.startsWith(root)) return;
  const route = decoded.slice(root.length);
  return isSafeCatalogueRoute(route) ? route : undefined;
}

/** Address generated bytes within a catalogue alongside authored closure resources. */
export function generatedResourcePath(route: string): string {
  return `${GENERATED_DIRECTORY}/${route}`;
}

/** Strip only the exact generated subtree prefix from a catalogue-relative resource. */
export function generatedResourceRoute(route: string): string | undefined {
  const prefix = `${GENERATED_DIRECTORY}/`;
  return route.startsWith(prefix) ? route.slice(prefix.length) : undefined;
}
