import path from "node:path";

import { isSafeRepositoryPath } from "@mokly/viewer/data";

import { MAX_BATCH_OUTPUT_BYTES } from "../review/git_batch.js";

import { joinCataloguePath } from "./catalogue.js";
import {
  ensureBaselineDirectory,
  confinedBaselineStat,
  validateOutputTree,
} from "./confinement.js";
import { BaselineError } from "./errors.js";
import type { HistoricalCatalogue } from "./manifest.js";
import type { BaselineFileSystem } from "./types.js";

/** Harvest only generated bytes and referenced authored resources for a v6 baseline. */
export async function harvestHistoricalCatalogue(
  fs: BaselineFileSystem,
  extraction: string,
  output: string,
  selected: HistoricalCatalogue,
  signal?: AbortSignal,
): Promise<void> {
  const { descriptor, manifest } = selected;
  if (descriptor.layout === "legacy") {
    const source = path.join(extraction, descriptor.catalogueRoot);
    await validateOutputTree(fs, source, signal);
    await fs.rename(source, output);
    return;
  }
  if (manifest.schemaVersion !== 6 || !("assetClosure" in manifest))
    throw new BaselineError(
      "baseline-output-invalid",
      "Invalid v6 baseline manifest",
    );
  await ensureBaselineDirectory(fs, path.dirname(output), output, signal);
  const destination = path.join(output, descriptor.generatedRoot);
  await ensureBaselineDirectory(fs, output, path.dirname(destination), signal);
  await fs.rename(path.join(extraction, descriptor.generatedRoot), destination);
  for (const route of manifest.assetClosure) {
    if (!isSafeRepositoryPath(route) || route.startsWith(".generated/"))
      throw new BaselineError(
        "baseline-output-invalid",
        `Invalid closure file: ${route}`,
      );
    const relative = joinCataloguePath(descriptor.catalogueRoot, route);
    const stat = await confinedBaselineStat(fs, extraction, relative, signal);
    if (stat?.kind !== "regular")
      throw new BaselineError(
        "baseline-output-invalid",
        `Missing authored baseline asset: ${route}`,
      );
    const target = path.join(output, relative);
    await ensureBaselineDirectory(fs, output, path.dirname(target), signal);
    await fs.write(
      target,
      await fs.read(path.join(extraction, relative), MAX_BATCH_OUTPUT_BYTES),
    );
  }
}
