import fs from "node:fs/promises";
import path from "node:path";
import type { TestContext } from "node:test";

import { readManifest } from "../../dist/registry/manifest.js";
import { readBaseManifest } from "../../dist/review/base_manifest.js";
import {
  NodeGitCommandRunner,
  CommittedRepository,
} from "../../dist/review/git.js";

import { changedFixture } from "./changed_fixture.js";

export const pageDocument =
  '<!doctype html><html><head><link rel="stylesheet" href="document.css"></head><body><!--mokly-review-ignore:start:nav--><nav>Old navigation</nav><!--mokly-review-ignore:end:nav--><main>Document content</main></body></html>';

/** Commit a v2/v3 document baseline, then restore the registered v4 page. */
export async function historicalPageFixture(
  context: TestContext,
  version: 2 | 3,
  options: {
    document?: string;
    route?: string;
    sourcePath?: string;
    symlink?: boolean;
  } = {},
) {
  const source = `import { defineCollection, definePage } from "@mokly/mokly";
const meta = { description: "Document", relatedDocs: [] };
export const mockups = [
  defineCollection({ ...meta, id: "documents", title: "Documents", childIds: ["handbook"] }),
  definePage({ ...meta, id: "handbook", title: "Current handbook", route: "handbook.html", render: () => ${JSON.stringify(pageDocument)} })
];`;
  const fixture = await changedFixture(
    context,
    source,
    {
      extraConfig: `compatibility: { readManifestV2: ${version === 2} },`,
    },
    async (fixture) => {
      await fs.writeFile(
        path.join(fixture.mockupsDir, "document.css"),
        "body { color: red; }",
      );
    },
  );
  const manifest = readManifest(fixture.config);
  const manifestPath = path.join(fixture.mockupsDir, "mokly-manifest.json");
  const currentManifest = await fs.readFile(manifestPath);
  const currentPath = path.join(fixture.mockupsDir, "handbook.html");
  const currentDocument = await fs.readFile(currentPath, "utf8");
  const route = options.route ?? "handbook.html";
  const sourcePath =
    options.sourcePath ?? "mockups/legacy/handbook.source.html";
  const historical = {
    entries: [],
    generatedBy: version === 2 ? "mockbook" : "mokly",
    legacyPages: [
      { route, sourcePath },
      {
        route: "obsolete.html",
        sourcePath: "mockups/legacy/obsolete.source.html",
      },
    ],
    schemaVersion: version,
  };
  const historicalPath =
    version === 2
      ? path.join(fixture.mockupsDir, "mockbook-manifest.json")
      : manifestPath;
  if (version === 2) await fs.rm(manifestPath);
  await fs.writeFile(historicalPath, JSON.stringify(historical));
  const artifact = path.join(fixture.mockupsDir, route);
  await fs.rm(currentPath);
  if (options.symlink) await fs.symlink("document.css", artifact);
  else
    await fs.writeFile(
      artifact,
      `<!-- Generated by mokly from ${sourcePath}. Do not edit. -->\n${options.document ?? pageDocument}\n`,
    );
  fixture.git("add", "-A");
  fixture.git("commit", "-qm", "test: historical page baseline");
  const commit = fixture.git("rev-parse", "HEAD").toString().trim();
  const client = new CommittedRepository(
    new NodeGitCommandRunner(fixture.root),
  );
  const baseline = await readBaseManifest(
    client.reader,
    commit,
    fixture.config,
  );
  await fs.rm(artifact);
  if (version === 2) await fs.rm(historicalPath);
  await fs.writeFile(manifestPath, currentManifest);
  await fs.writeFile(currentPath, currentDocument);
  return {
    ...fixture,
    baseline,
    client,
    commit,
    currentDocument,
    currentPath,
    manifest,
  };
}
